import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // mainSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // Or create a sidebar manually
  mainSidebar: [
    'index',
    'architecture/index',
    'block-controls/index',
    'plan/index',
    // {
    //   type: 'link',
    //   href: '/sandbox',
    //   label: 'Sandbox',
    //   customProps: {
    //     draft: true
    //   }
    // },
    // https://docusaurus.io/docs/sidebar/items
    // {
    //   type: 'category',
    //   label: 'Components',
    //   link: {
    //     type: 'generated-index',
    //     title: 'Components',
    //   },
    //   items: [{ type: 'autogenerated', dirName: 'components' }],
    //   // collapsed: false,
    // },

    // {
    //   type: 'category',
    //   label: 'Form',
    //   // link: {
    //   //   type: 'doc',
    //   //   id: 'form/index'
    //   //   // type: 'generated-index',
    //   //   // title: 'Form',
    //   // },
    //   items: [{ type: 'autogenerated', dirName: 'form' }],
    //   // collapsed: false,
    // },
    // // { type: 'html', value: `<hr>` },
    // // 'content',
    // // 'layout',
    // // 'utilities',

    // // { type: 'autogenerated', dirName: 'examples' },

    // [
    //   {
    //     type: 'html',
    //     value: `<hr><b style="margin-left:.75rem;">Example Pages</b>`,
    //   },
    //   { type: 'link', label: 'Album', href: '/examples/album' },
    //   { type: 'link', label: 'Badges', href: '/examples/badges' },
    //   { type: 'link', label: 'Blog', href: '/examples/blog' },
  ],
}

export default sidebars
