name: Run Tests
permissions:
  contents: write
on:
  push:
    branches-ignore:
      - main
  workflow_call:
jobs:
  tests:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.TANGIBLE_PIPELINE_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpunit-polyfills
      - name: Git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --optimize-autoloader
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: |
          echo "https://TangibleInc:$ACCESS_TOKEN@github.com" >> $HOME/.git-credentials
          git config --global credential.helper store
          bun install
          rm -rf ${HOME}/.git-credentials
      - name: Install dev plugins
        run: bun --bun run install:dev
      - name: Install playwright
        run: bun run e2e:install
      - name: PHPUnit - Run tests for PHP 7.4
        run: bun run test:7.4
      - name: End to end - Run tests for PHP 7.4
        run: bun run e2e
      - name: PHPUnit - Run tests for PHP 8.2
        run: bun run test:8.2
      - name: End to end - Run tests for PHP 8.2
        run: bun run e2e
      - name: PHPUnit - Run tests for PHP 8.4
        run: bun run test:8.4
      - name: End to end - Run tests for PHP 8.4
        run: bun run e2e
